In [1]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv('Hr_data.csv')

In [11]:
df

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [14]:
df.isna().sum()

employee_id              0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
department               0
salary                   0
dtype: int64

In [15]:
df.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [16]:
df.columns

Index(['employee_id', 'number_project', 'average_montly_hours',
       'time_spend_company', 'Work_accident', 'left', 'promotion_last_5years',
       'department', 'salary'],
      dtype='str')

In [17]:
df.rename(columns={'employee_id' : 'Employee_ID', 'number_project' : 'Number_of_Projects', 'average_montly_hours' : 'Average_Monthly_Hours',
       'time_spend_company' : 'Time_Spent_in_Company', 'Work_accident' : 'Work_Accident', 'left' : 'Left', 'promotion_last_5years' : 'Promoted_in_Last_5_Years',
       'department' : 'Department', 'salary' : 'Salary '}, inplace=True)

In [18]:
df

,Employee_ID,Number_of_Projects,Average_Monthly_Hours,Time_Spent_in_Company,Work_Accident,Left,Promoted_in_Last_5_Years,Department,Salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [19]:
df['Department'].value_counts()

Department
sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: count, dtype: int64

In [31]:
df.columns

Index(['Employee_ID', 'Number_of_Projects', 'Average_Monthly_Hours',
       'Time_Spent_in_Company', 'Work_Accident', 'Left',
       'Promoted_in_Last_5_Years', 'Department', 'Salary '],
      dtype='str')

In [33]:
df.loc[df['Salary '] == 'low', ['Employee_ID','Department', 'Salary ']]

       Employee_ID Department Salary
0             1003      sales     low
3             1038      sales     low
4             1057      sales     low
5             1060      sales     low
6             1061      sales     low
...            ...        ...     ...
14994        87670    support     low
14995        87673    support     low
14996        87679    support     low
14997        87681    support     low
14998        87684    support     low

[7316 rows x 3 columns]

In [34]:
df.iloc[0:5, 0:5]

,Employee_ID,Number_of_Projects,Average_Monthly_Hours,Time_Spent_in_Company,Work_Accident
0,1003,2,157,3,0
1,1005,5,262,6,0
2,1486,7,272,4,0
3,1038,5,223,5,0
4,1057,2,159,3,0

In [36]:
df['Department'].unique()

<ArrowStringArray>
[      'sales',  'accounting',          'hr',   'technical',     'support',
  'management',          'IT', 'product_mng',   'marketing',       'RandD']
Length: 10, dtype: str

In [40]:
df.loc[df['Department'].isin(['Sales', 'IT'])]

,Employee_ID,Number_of_Projects,Average_Monthly_Hours,Time_Spent_in_Company,Work_Accident,Left,Promoted_in_Last_5_Years,Department,Salary
61,1399,7,308,4,0,1,0,IT,medium
62,1404,6,244,5,0,1,0,IT,medium
63,1413,2,132,3,0,1,0,IT,medium
64,42423,6,286,4,0,1,0,IT,medium
65,1424,6,161,4,0,1,0,IT,medium
...,...,...,...,...,...,...,...,...,...
14930,87284,6,268,4,0,1,0,IT,medium
14931,87288,5,240,5,0,1,0,IT,medium
14932,87294,2,127,3,0,1,0,IT,medium
14933,87308,7,264,4,0,1,0,IT,medium
14938,45511,4,271,5,0,1,0,IT,medium

In [54]:
df['Department'].value_counts()

Department
sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: count, dtype: int64