In [1]:
import pandas as pd

In [2]:
pd.Series([10,20,30])

0    10
1    20
2    30
dtype: int64

In [3]:
data = [['Sangu', 21, 'DS'],['Eren', 20, 'BSc']]
dff = pd.DataFrame(data, index = ['a', 'b'], columns = ['Names', 'Age', 'Branch'])

In [4]:
dff['Names']

a    Sangu
b     Eren
Name: Names, dtype: str

In [5]:
dff.loc['a', 'Names'] = 'Sanji'

In [6]:
dff

   Names  Age Branch
a  Sanji   21     DS
b   Eren   20    BSc

In [7]:
df = pd.read_csv('Titanic.csv')

In [8]:
df.to_csv("csv", index=False)

In [9]:
df.to_csv("Titanic.csv", index=False)

In [10]:
df.rename(columns={'pclass':'Passenger Class','cabin':'Cabin','ticket':'Ticket','embarked':'Embarked','survived':'Survived','name':'Full_Name','sex':'Gender', 'age':'Age', 'fare':'Fare','sibsp':'Siblings/Spouses', 'parch':'Parents/Children'}, inplace=True)

In [11]:
df

,Passenger Class,Full_Name,Gender,Age,Siblings/Spouses,Parents/Children,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [12]:
df.head()

,Passenger Class,Full_Name,Gender,Age,Siblings/Spouses,Parents/Children,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [13]:
df.tail()

,Passenger Class,Full_Name,Gender,Age,Siblings/Spouses,Parents/Children,Ticket,Fare,Cabin,Embarked,Survived
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

In [14]:
df.columns

Index(['Passenger Class', 'Full_Name', 'Gender', 'Age', 'Siblings/Spouses',
       'Parents/Children', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Survived'],
      dtype='str')

In [15]:
df['Gender'].unique()

<ArrowStringArray>
['female', 'male']
Length: 2, dtype: str

In [16]:
df['Gender'].value_counts()

Gender
male      843
female    466
Name: count, dtype: int64

In [17]:
df.shape

(1309, 11)

In [18]:
#loc >>> To fetch a row or column by label
df.loc[0]

Passenger Class                                 1
Full_Name           Allen, Miss. Elisabeth Walton
Gender                                     female
Age                                          29.0
Siblings/Spouses                                0
Parents/Children                                0
Ticket                                      24160
Fare                                     211.3375
Cabin                                          B5
Embarked                                        S
Survived                                        1
Name: 0, dtype: object

In [19]:
df.loc[0:5, ['Full_Name', 'Gender', 'Age']]

                                         Full_Name  Gender      Age
0                    Allen, Miss. Elisabeth Walton  female  29.0000
1                   Allison, Master. Hudson Trevor    male   0.9167
2                     Allison, Miss. Helen Loraine  female   2.0000
3             Allison, Mr. Hudson Joshua Creighton    male  30.0000
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000
5                              Anderson, Mr. Harry    male  48.0000

In [20]:
df.loc[df['Age'] > 30, ['Full_Name', 'Gender', 'Age']]

                                            Full_Name  Gender   Age
5                                 Anderson, Mr. Harry    male  48.0
6                   Andrews, Miss. Kornelia Theodosia  female  63.0
7                              Andrews, Mr. Thomas Jr    male  39.0
8       Appleton, Mrs. Edward Dale (Charlotte Lamson)  female  53.0
9                             Artagaveytia, Mr. Ramon    male  71.0
...                                               ...     ...   ...
1286  Whabee, Mrs. George Joseph (Shawneene Abi-Saab)  female  38.0
1287                 Widegren, Mr. Carl/Charles Peter    male  51.0
1290                 Wilkes, Mrs. James (Ellen Needs)  female  47.0
1298                        Wittevrongel, Mr. Camille    male  36.0
1301                             Youseff, Mr. Gerious    male  45.5

[437 rows x 3 columns]

In [21]:
df.loc[((df['Age'] > 30) | (df['Gender'] == 'male')) & ((df['Embarked'] == 'S') | (df['Embarked'] == 'C'))].head()

,Passenger Class,Full_Name,Gender,Age,Siblings/Spouses,Parents/Children,Ticket,Fare,Cabin,Embarked,Survived
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
5,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.5500,E12,S,1
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0000,1,0,13502,77.9583,D7,S,1
7,1,"Andrews, Mr. Thomas Jr",male,39.0000,0,0,112050,0.0000,A36,S,0

In [22]:
df.loc[[0, 1, 2], ['Full_Name', 'Gender', 'Age']]

                        Full_Name  Gender      Age
0   Allen, Miss. Elisabeth Walton  female  29.0000
1  Allison, Master. Hudson Trevor    male   0.9167
2    Allison, Miss. Helen Loraine  female   2.0000

In [23]:
df.loc[df['Passenger Class'].isin([1,2]) & df['Cabin'].isin(['B5','C22 C26'])]

,Passenger Class,Full_Name,Gender,Age,Siblings/Spouses,Parents/Children,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
193,1,"Madill, Miss. Georgette Alexandra",female,15.0000,0,1,24160,211.3375,B5,S,1

In [24]:
df.loc[df['Age'].between(20, 30, inclusive='right')]

,Passenger Class,Full_Name,Gender,Age,Siblings/Spouses,Parents/Children,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,1
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,0
12,1,"Aubart, Mme. Leontine Pauline",female,24.0,0,0,PC 17477,69.3000,B35,C,1
13,1,"Barber, Miss. Ellen ""Nellie""",female,26.0,0,0,19877,78.8500,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...
1296,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0
1299,3,"Yasbeck, Mr. Antoni",male,27.0,1,0,2659,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

In [28]:
# df.iloc[0]
df.iloc[0 : 8]

,Passenger Class,Full_Name,Gender,Age,Siblings/Spouses,Parents/Children,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
5,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.5500,E12,S,1
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0000,1,0,13502,77.9583,D7,S,1
7,1,"Andrews, Mr. Thomas Jr",male,39.0000,0,0,112050,0.0000,A36,S,0