In [2]:
import pandas as pd

In [3]:
pd.Series([10,20,30])

0    10
1    20
2    30
dtype: int64

In [4]:
data = [['Sangu', 21, 'DS'],['Eren', 20, 'BSc']]
dff = pd.DataFrame(data, index = ['a', 'b'], columns = ['Names', 'Age', 'Branch'])

In [5]:
dff['Names']

a    Sangu
b     Eren
Name: Names, dtype: str

In [6]:
dff.loc['a', 'Names'] = 'Sanji'

In [7]:
dff

   Names  Age Branch
a  Sanji   21     DS
b   Eren   20    BSc

In [8]:
df = pd.read_csv('Titanic.csv')

In [9]:
df.to_csv("csv", index=False)

In [10]:
df.to_csv("Titanic.csv", index=False)

In [11]:
df.rename(columns={'pclass':'Passenger Class','cabin':'Cabin','ticket':'Ticket','embarked':'Embarked','survived':'Survived','name':'Full_Name','sex':'Gender', 'age':'Age', 'fare':'Fare','sibsp':'Siblings/Spouses', 'parch':'Parents/Children'}, inplace=True)

In [12]:
df

,Passenger Class,Full_Name,Gender,Age,Siblings/Spouses,Parents/Children,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [13]:
df.head()

,Passenger Class,Full_Name,Gender,Age,Siblings/Spouses,Parents/Children,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [14]:
df.tail()

,Passenger Class,Full_Name,Gender,Age,Siblings/Spouses,Parents/Children,Ticket,Fare,Cabin,Embarked,Survived
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

In [18]:
df.columns

Index(['Passenger Class', 'Full_Name', 'Gender', 'Age', 'Siblings/Spouses',
       'Parents/Children', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Survived'],
      dtype='str')

In [19]:
df['Gender'].unique()

<ArrowStringArray>
['female', 'male']
Length: 2, dtype: str

In [20]:
df['Gender'].value_counts()

Gender
male      843
female    466
Name: count, dtype: int64