In [3]:
import pandas as pd
import numpy as np

In [4]:
# df = pd.read_csv(r"https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/amazon_fires.csv",encoding="ISO-8859-1")

In [5]:
# df

In [6]:
# df.columns

In [7]:
# df.rename(columns={'ano':'year','mes' : 'month', 'estado' : "state", 'numero': 'no_of_fires', 'encontro': 'date'}, inplace=True)

In [8]:
# df['month'].unique()

In [9]:
# df['no_of_fires'] = df['no_of_fires'].str.strip(' Fires')

In [10]:
# df['month'] = df['month'].replace({'Janeiro':'Jan', 'Fevereiro': 'Feb',     'Março':'Mar',     'Abril':'Apr',      'Maio':'May',     'Junho':'Jun',
     # 'Julho':'Jul',    'Agosto':'Aug',  'Setembro':'Sep',   'Outubro':'Oct',  'Novembro':'Nov',  'Dezembro':'Dec'},inplace=True)

In [11]:
# df.to_csv('Amazon_Fires.csv', index=False)

In [12]:
df = pd.read_csv('Amazon_Fires.csv')

In [13]:
df

      year month      state  no_of_fires      date
0     1998   Jan       Acre          0.0  1/1/1998
1     1999   Jan       Acre          0.0  1/1/1999
2     2000   Jan       Acre          0.0  1/1/2000
3     2001   Jan       Acre          0.0  1/1/2001
4     2002   Jan       Acre          0.0  1/1/2002
...    ...   ...        ...          ...       ...
6449  2012   Dec  Tocantins        128.0  1/1/2012
6450  2013   Dec  Tocantins         85.0  1/1/2013
6451  2014   Dec  Tocantins        223.0  1/1/2014
6452  2015   Dec  Tocantins        373.0  1/1/2015
6453  2016   Dec  Tocantins        119.0  1/1/2016

[6454 rows x 5 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         6454 non-null   int64
 1   month        6454 non-null   object
 2   state        6454 non-null   object
 3   no_of_fires  6322 non-null   float64
 4   date         6454 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 252.2+ KB

In [15]:
df.isna().sum()

year             0
month            0
state            0
no_of_fires    132
date             0
dtype: int64

In [16]:
df.dropna()

      year month      state  no_of_fires      date
0     1998   Jan       Acre          0.0  1/1/1998
1     1999   Jan       Acre          0.0  1/1/1999
2     2000   Jan       Acre          0.0  1/1/2000
3     2001   Jan       Acre          0.0  1/1/2001
4     2002   Jan       Acre          0.0  1/1/2002
...    ...   ...        ...          ...       ...
6449  2012   Dec  Tocantins        128.0  1/1/2012
6450  2013   Dec  Tocantins         85.0  1/1/2013
6451  2014   Dec  Tocantins        223.0  1/1/2014
6452  2015   Dec  Tocantins        373.0  1/1/2015
6453  2016   Dec  Tocantins        119.0  1/1/2016

[6322 rows x 5 columns]

In [17]:
df.dropna(how = 'any')

      year month      state  no_of_fires      date
0     1998   Jan       Acre          0.0  1/1/1998
1     1999   Jan       Acre          0.0  1/1/1999
2     2000   Jan       Acre          0.0  1/1/2000
3     2001   Jan       Acre          0.0  1/1/2001
4     2002   Jan       Acre          0.0  1/1/2002
...    ...   ...        ...          ...       ...
6449  2012   Dec  Tocantins        128.0  1/1/2012
6450  2013   Dec  Tocantins         85.0  1/1/2013
6451  2014   Dec  Tocantins        223.0  1/1/2014
6452  2015   Dec  Tocantins        373.0  1/1/2015
6453  2016   Dec  Tocantins        119.0  1/1/2016

[6322 rows x 5 columns]

In [18]:
df.dropna(how='all', axis=1)

      year month      state  no_of_fires      date
0     1998   Jan       Acre          0.0  1/1/1998
1     1999   Jan       Acre          0.0  1/1/1999
2     2000   Jan       Acre          0.0  1/1/2000
3     2001   Jan       Acre          0.0  1/1/2001
4     2002   Jan       Acre          0.0  1/1/2002
...    ...   ...        ...          ...       ...
6449  2012   Dec  Tocantins        128.0  1/1/2012
6450  2013   Dec  Tocantins         85.0  1/1/2013
6451  2014   Dec  Tocantins        223.0  1/1/2014
6452  2015   Dec  Tocantins        373.0  1/1/2015
6453  2016   Dec  Tocantins        119.0  1/1/2016

[6454 rows x 5 columns]

In [19]:
df.bfill()

      year month      state  no_of_fires      date
0     1998   Jan       Acre          0.0  1/1/1998
1     1999   Jan       Acre          0.0  1/1/1999
2     2000   Jan       Acre          0.0  1/1/2000
3     2001   Jan       Acre          0.0  1/1/2001
4     2002   Jan       Acre          0.0  1/1/2002
...    ...   ...        ...          ...       ...
6449  2012   Dec  Tocantins        128.0  1/1/2012
6450  2013   Dec  Tocantins         85.0  1/1/2013
6451  2014   Dec  Tocantins        223.0  1/1/2014
6452  2015   Dec  Tocantins        373.0  1/1/2015
6453  2016   Dec  Tocantins        119.0  1/1/2016

[6454 rows x 5 columns]

In [20]:
df.ffill()

      year month      state  no_of_fires      date
0     1998   Jan       Acre          0.0  1/1/1998
1     1999   Jan       Acre          0.0  1/1/1999
2     2000   Jan       Acre          0.0  1/1/2000
3     2001   Jan       Acre          0.0  1/1/2001
4     2002   Jan       Acre          0.0  1/1/2002
...    ...   ...        ...          ...       ...
6449  2012   Dec  Tocantins        128.0  1/1/2012
6450  2013   Dec  Tocantins         85.0  1/1/2013
6451  2014   Dec  Tocantins        223.0  1/1/2014
6452  2015   Dec  Tocantins        373.0  1/1/2015
6453  2016   Dec  Tocantins        119.0  1/1/2016

[6454 rows x 5 columns]

In [21]:
df.drop(columns=['date'])

      year month      state  no_of_fires
0     1998   Jan       Acre          0.0
1     1999   Jan       Acre          0.0
2     2000   Jan       Acre          0.0
3     2001   Jan       Acre          0.0
4     2002   Jan       Acre          0.0
...    ...   ...        ...          ...
6449  2012   Dec  Tocantins        128.0
6450  2013   Dec  Tocantins         85.0
6451  2014   Dec  Tocantins        223.0
6452  2015   Dec  Tocantins        373.0
6453  2016   Dec  Tocantins        119.0

[6454 rows x 4 columns]

In [22]:
df.drop([0,2,4,6])

      year month      state  no_of_fires      date
1     1999   Jan       Acre          0.0  1/1/1999
3     2001   Jan       Acre          0.0  1/1/2001
5     2003   Jan       Acre         10.0  1/1/2003
7     2005   Jan       Acre         12.0  1/1/2005
8     2006   Jan       Acre          4.0  1/1/2006
...    ...   ...        ...          ...       ...
6449  2012   Dec  Tocantins        128.0  1/1/2012
6450  2013   Dec  Tocantins         85.0  1/1/2013
6451  2014   Dec  Tocantins        223.0  1/1/2014
6452  2015   Dec  Tocantins        373.0  1/1/2015
6453  2016   Dec  Tocantins        119.0  1/1/2016

[6450 rows x 5 columns]

In [23]:
df.reset_index(drop=True)

      year month      state  no_of_fires      date
0     1998   Jan       Acre          0.0  1/1/1998
1     1999   Jan       Acre          0.0  1/1/1999
2     2000   Jan       Acre          0.0  1/1/2000
3     2001   Jan       Acre          0.0  1/1/2001
4     2002   Jan       Acre          0.0  1/1/2002
...    ...   ...        ...          ...       ...
6449  2012   Dec  Tocantins        128.0  1/1/2012
6450  2013   Dec  Tocantins         85.0  1/1/2013
6451  2014   Dec  Tocantins        223.0  1/1/2014
6452  2015   Dec  Tocantins        373.0  1/1/2015
6453  2016   Dec  Tocantins        119.0  1/1/2016

[6454 rows x 5 columns]

In [24]:
df.set_index('year', inplace=True)

In [25]:
df

     month      state  no_of_fires      date
year
1998   Jan       Acre          0.0  1/1/1998
1999   Jan       Acre          0.0  1/1/1999
2000   Jan       Acre          0.0  1/1/2000
2001   Jan       Acre          0.0  1/1/2001
2002   Jan       Acre          0.0  1/1/2002
...    ...        ...          ...       ...
2012   Dec  Tocantins        128.0  1/1/2012
2013   Dec  Tocantins         85.0  1/1/2013
2014   Dec  Tocantins        223.0  1/1/2014
2015   Dec  Tocantins        373.0  1/1/2015
2016   Dec  Tocantins        119.0  1/1/2016

[6454 rows x 4 columns]

In [26]:
df.sort_index().iloc[320:330]

     month             state  no_of_fires      date
year
1998   Dec         Tocantins          9.0  1/1/1998
1998   Feb               Rio          0.0  1/1/1998
1998   Aug               Rio         21.0  1/1/1998
1998   Jun              Piau         46.0  1/1/1998
1999   Dec           Paraiba        254.0  1/1/1999
1999   Apr  Distrito Federal          0.0  1/1/1999
1999   May  Distrito Federal          0.0  1/1/1999
1999   Jul           Roraima          4.0  1/1/1999
1999   May         Tocantins         24.0  1/1/1999
1999   Jul              Piau        123.0  1/1/1999

In [27]:
df.drop_duplicates(keep='last')

     month      state  no_of_fires      date
year
1998   Jan       Acre          0.0  1/1/1998
1999   Jan       Acre          0.0  1/1/1999
2000   Jan       Acre          0.0  1/1/2000
2001   Jan       Acre          0.0  1/1/2001
2002   Jan       Acre          0.0  1/1/2002
...    ...        ...          ...       ...
2012   Dec  Tocantins        128.0  1/1/2012
2013   Dec  Tocantins         85.0  1/1/2013
2014   Dec  Tocantins        223.0  1/1/2014
2015   Dec  Tocantins        373.0  1/1/2015
2016   Dec  Tocantins        119.0  1/1/2016

[6424 rows x 4 columns]

In [28]:
df.duplicated()

year
1998    False
1999    False
2000    False
2001    False
2002    False
        ...
2012    False
2013    False
2014    False
2015    False
2016    False
Length: 6454, dtype: bool

In [29]:
df.duplicated().sum()

np.int64(30)

In [30]:
df[df.duplicated()].head()

     month        state  no_of_fires      date
year
2017   Jan      alagoas         38.0  1/1/2017
1998   Jan  Mato Grosso          0.0  1/1/1998
1998   Feb  Mato Grosso          0.0  1/1/1998
1998   Mar  Mato Grosso          0.0  1/1/1998
1998   May  Mato Grosso          0.0  1/1/1998

In [31]:
df.loc[2000]

     month      state  no_of_fires      date
year
2000   Jan       Acre        0.000  1/1/2000
2000   Feb       Acre        0.000  1/1/2000
2000   Mar       Acre       11.000  1/1/2000
2000   Apr       Acre        1.000  1/1/2000
2000   May       Acre        1.000  1/1/2000
...    ...        ...          ...       ...
2000   Aug  Tocantins        1.949  1/1/2000
2000   Sep  Tocantins        2.552  1/1/2000
2000   Oct  Tocantins        1.053  1/1/2000
2000   Nov  Tocantins       96.000  1/1/2000
2000   Dec  Tocantins       20.000  1/1/2000

[324 rows x 4 columns]

In [32]:
df.index

Index([1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
       ...
       2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016],
      dtype='int64', name='year', length=6454)

In [34]:
df['no_of_fires'].sort_values(ascending=True, na_position='last')

year
1998    0.0
2001    0.0
2013    0.0
1999    0.0
2002    0.0
       ...
2008    NaN
2017    NaN
2006    NaN
1998    NaN
2011    NaN
Name: no_of_fires, Length: 6454, dtype: float64