In [3]:
import pandas as pd
import numpy as np

In [4]:
# df = pd.read_csv(r"https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/amazon_fires.csv",encoding="ISO-8859-1")

In [5]:
# df

In [6]:
# df.columns

In [7]:
# df.rename(columns={'ano':'year','mes' : 'month', 'estado' : "state", 'numero': 'no_of_fires', 'encontro': 'date'}, inplace=True)

In [8]:
# df['month'].unique()

In [9]:
# df['no_of_fires'] = df['no_of_fires'].str.strip(' Fires')

In [10]:
# df['month'] = df['month'].replace({'Janeiro':'Jan', 'Fevereiro': 'Feb',     'Março':'Mar',     'Abril':'Apr',      'Maio':'May',     'Junho':'Jun',
     # 'Julho':'Jul',    'Agosto':'Aug',  'Setembro':'Sep',   'Outubro':'Oct',  'Novembro':'Nov',  'Dezembro':'Dec'},inplace=True)

In [11]:
# df.to_csv('Amazon_Fires.csv', index=False)

In [12]:
df = pd.read_csv('Amazon_Fires.csv')

In [13]:
df

      year month      state  no_of_fires      date
0     1998   Jan       Acre          0.0  1/1/1998
1     1999   Jan       Acre          0.0  1/1/1999
2     2000   Jan       Acre          0.0  1/1/2000
3     2001   Jan       Acre          0.0  1/1/2001
4     2002   Jan       Acre          0.0  1/1/2002
...    ...   ...        ...          ...       ...
6449  2012   Dec  Tocantins        128.0  1/1/2012
6450  2013   Dec  Tocantins         85.0  1/1/2013
6451  2014   Dec  Tocantins        223.0  1/1/2014
6452  2015   Dec  Tocantins        373.0  1/1/2015
6453  2016   Dec  Tocantins        119.0  1/1/2016

[6454 rows x 5 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         6454 non-null   int64
 1   month        6454 non-null   object
 2   state        6454 non-null   object
 3   no_of_fires  6322 non-null   float64
 4   date         6454 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 252.2+ KB

In [17]:
df.isna().sum()

year             0
month            0
state            0
no_of_fires    132
date             0
dtype: int64

In [19]:
df.dropna()

      year month      state  no_of_fires      date
0     1998   Jan       Acre          0.0  1/1/1998
1     1999   Jan       Acre          0.0  1/1/1999
2     2000   Jan       Acre          0.0  1/1/2000
3     2001   Jan       Acre          0.0  1/1/2001
4     2002   Jan       Acre          0.0  1/1/2002
...    ...   ...        ...          ...       ...
6449  2012   Dec  Tocantins        128.0  1/1/2012
6450  2013   Dec  Tocantins         85.0  1/1/2013
6451  2014   Dec  Tocantins        223.0  1/1/2014
6452  2015   Dec  Tocantins        373.0  1/1/2015
6453  2016   Dec  Tocantins        119.0  1/1/2016

[6322 rows x 5 columns]

In [21]:
df.dropna(how = 'any')

      year month      state  no_of_fires      date
0     1998   Jan       Acre          0.0  1/1/1998
1     1999   Jan       Acre          0.0  1/1/1999
2     2000   Jan       Acre          0.0  1/1/2000
3     2001   Jan       Acre          0.0  1/1/2001
4     2002   Jan       Acre          0.0  1/1/2002
...    ...   ...        ...          ...       ...
6449  2012   Dec  Tocantins        128.0  1/1/2012
6450  2013   Dec  Tocantins         85.0  1/1/2013
6451  2014   Dec  Tocantins        223.0  1/1/2014
6452  2015   Dec  Tocantins        373.0  1/1/2015
6453  2016   Dec  Tocantins        119.0  1/1/2016

[6322 rows x 5 columns]

In [28]:
df.dropna(how='all', axis=1)

      year month      state  no_of_fires      date
0     1998   Jan       Acre          0.0  1/1/1998
1     1999   Jan       Acre          0.0  1/1/1999
2     2000   Jan       Acre          0.0  1/1/2000
3     2001   Jan       Acre          0.0  1/1/2001
4     2002   Jan       Acre          0.0  1/1/2002
...    ...   ...        ...          ...       ...
6449  2012   Dec  Tocantins        128.0  1/1/2012
6450  2013   Dec  Tocantins         85.0  1/1/2013
6451  2014   Dec  Tocantins        223.0  1/1/2014
6452  2015   Dec  Tocantins        373.0  1/1/2015
6453  2016   Dec  Tocantins        119.0  1/1/2016

[6454 rows x 5 columns]

In [29]:
df.bfill()

      year month      state  no_of_fires      date
0     1998   Jan       Acre          0.0  1/1/1998
1     1999   Jan       Acre          0.0  1/1/1999
2     2000   Jan       Acre          0.0  1/1/2000
3     2001   Jan       Acre          0.0  1/1/2001
4     2002   Jan       Acre          0.0  1/1/2002
...    ...   ...        ...          ...       ...
6449  2012   Dec  Tocantins        128.0  1/1/2012
6450  2013   Dec  Tocantins         85.0  1/1/2013
6451  2014   Dec  Tocantins        223.0  1/1/2014
6452  2015   Dec  Tocantins        373.0  1/1/2015
6453  2016   Dec  Tocantins        119.0  1/1/2016

[6454 rows x 5 columns]

In [30]:
df.ffill()

      year month      state  no_of_fires      date
0     1998   Jan       Acre          0.0  1/1/1998
1     1999   Jan       Acre          0.0  1/1/1999
2     2000   Jan       Acre          0.0  1/1/2000
3     2001   Jan       Acre          0.0  1/1/2001
4     2002   Jan       Acre          0.0  1/1/2002
...    ...   ...        ...          ...       ...
6449  2012   Dec  Tocantins        128.0  1/1/2012
6450  2013   Dec  Tocantins         85.0  1/1/2013
6451  2014   Dec  Tocantins        223.0  1/1/2014
6452  2015   Dec  Tocantins        373.0  1/1/2015
6453  2016   Dec  Tocantins        119.0  1/1/2016

[6454 rows x 5 columns]