In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/amazon_fires.csv",encoding="ISO-8859-1")

In [4]:
df

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [7]:
df.columns

Index(['ano', 'mes', 'estado', 'numero', 'encontro'], dtype='str')

In [11]:
df.rename(columns={'ano':'year','mes' : 'month', 'estado' : "state", 'numero': 'no_of_fires', 'encontro': 'date'}, inplace=True)

In [18]:
df['month'].unique()

<ArrowStringArray>
[  'Janeiro', 'Fevereiro',     'Março',     'Abril',      'Maio',     'Junho',
     'Julho',    'Agosto',  'Setembro',   'Outubro',  'Novembro',  'Dezembro']
Length: 12, dtype: str

In [15]:
df['no_of_fires'] = df['no_of_fires'].str.strip(' Fires')

In [16]:
df['month'] = df['month'].replace({'Janeiro':'Jan', 'Fevereiro': 'Feb',     'Março':'Mar',     'Abril':'Apr',      'Maio':'May',     'Junho':'Jun',
     'Julho',    'Agosto',  'Setembro',   'Outubro',  'Novembro',  'Dezembro'})

      year     month      state no_of_fires      date
0     1998   Janeiro       Acre           0  1/1/1998
1     1999   Janeiro       Acre           0  1/1/1999
2     2000   Janeiro       Acre           0  1/1/2000
3     2001   Janeiro       Acre           0  1/1/2001
4     2002   Janeiro       Acre           0  1/1/2002
...    ...       ...        ...         ...       ...
6449  2012  Dezembro  Tocantins         128  1/1/2012
6450  2013  Dezembro  Tocantins          85  1/1/2013
6451  2014  Dezembro  Tocantins         223  1/1/2014
6452  2015  Dezembro  Tocantins         373  1/1/2015
6453  2016  Dezembro  Tocantins         119  1/1/2016

[6454 rows x 5 columns]